// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMosRBC_fLrBVawvqc2CgToIiJ178b9Zk',
    appId: '1:701052991536:android:09e4460b13038ce16f15f5',
    messagingSenderId: '701052991536',
    projectId: 'assignment-tracker-25fc1',
    storageBucket: 'assignment-tracker-25fc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS-5S_EHjjVieaKr7Q3iq-e8auYfl5F-k',
    appId: '1:701052991536:ios:b446167c3759cb1f6f15f5',
    messagingSenderId: '701052991536',
    projectId: 'assignment-tracker-25fc1',
    storageBucket: 'assignment-tracker-25fc1.firebasestorage.app',
    androidClientId: '701052991536-e3hgmbo6ihgtkp33ba4fabnaeg7fnnto.apps.googleusercontent.com',
    iosClientId: '701052991536-lr99rlbf914alge5q7ht0kai9et8s1vr.apps.googleusercontent.com',
    iosBundleId: 'com.assignmenttracker.assignmentTracker',
  );

}